package UI;

import ItensAcervo.discos;
import ItensAcervo.livros;
import javax.swing.JOptionPane;

public class TelaCadastrar extends javax.swing.JFrame {

    private int ed;

    public TelaCadastrar(boolean x) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/agenda (2).png")).getImage());
        if (x == true)
            JTP_LivrosDiscos.setSelectedIndex(0);
        else
            JTP_LivrosDiscos.setSelectedIndex(1);
    }
    public TelaCadastrar(){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTP_LivrosDiscos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JLabel_NomeLivro = new javax.swing.JLabel();
        JTF_NomeLivro = new javax.swing.JTextField();
        JLabel_Autor = new javax.swing.JLabel();
        JTF_AutorLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTF_EdicaoLivro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        JLabel_Nome1 = new javax.swing.JLabel();
        JTF_NomeDisco = new javax.swing.JTextField();
        JLabel_Autor1 = new javax.swing.JLabel();
        JTF_AutorDisco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JRad_Disco = new javax.swing.JRadioButton();
        JRad_CD = new javax.swing.JRadioButton();
        JB_Cadastar = new javax.swing.JButton();
        JB_Voltar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JLabel_Título = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);

        JLabel_NomeLivro.setText("Nome: ");

        JLabel_Autor.setText("Autor: ");

        jLabel3.setText("Edição:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(JLabel_Autor)
                    .addComponent(JLabel_NomeLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTF_NomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(JTF_AutorLivro)
                    .addComponent(JTF_EdicaoLivro))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_NomeLivro)
                    .addComponent(JTF_NomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_Autor)
                    .addComponent(JTF_AutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_EdicaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTP_LivrosDiscos.addTab("Livros", jPanel1);

        JLabel_Nome1.setText("Nome: ");

        JLabel_Autor1.setText("Autor: ");

        jLabel4.setText("Tipo:");

        JRad_Disco.setSelected(true);
        JRad_Disco.setText("Discos");
        JRad_Disco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRad_DiscoActionPerformed(evt);
            }
        });

        JRad_CD.setText("CDs");
        JRad_CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRad_CDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JLabel_Autor1)
                    .addComponent(JLabel_Nome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTF_NomeDisco, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(JTF_AutorDisco)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JRad_Disco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRad_CD)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_Nome1)
                    .addComponent(JTF_NomeDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_Autor1)
                    .addComponent(JTF_AutorDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JRad_Disco)
                    .addComponent(JRad_CD))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        JTP_LivrosDiscos.addTab("Discos", jPanel2);

        JB_Cadastar.setText("Cadastrar");
        JB_Cadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CadastarActionPerformed(evt);
            }
        });

        JB_Voltar.setText("Voltar");
        JB_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VoltarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        JLabel_Título.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Título.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Título.setText("Cadastrar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(JLabel_Título)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_Título, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JTP_LivrosDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_Cadastar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(JTP_LivrosDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Voltar)
                    .addComponent(JB_Cadastar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VoltarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_JB_VoltarActionPerformed

    private void JB_CadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CadastarActionPerformed
        if (JTP_LivrosDiscos.getSelectedIndex() == 0) {
            if ("".equals(JTF_NomeLivro.getText()) || "".equals(JTF_AutorLivro.getText())
                    || "".equals(JTF_EdicaoLivro.getText())) {
                JOptionPane.showMessageDialog(null, "É necessário preencher todos os dados!");
            } else {
                if (converter()) {
                    livros liv = new livros();
                    liv.cadastro(JTF_NomeLivro.getText(), JTF_AutorLivro.getText(), getEd());
                    JTF_NomeLivro.setText("");
                    JTF_AutorLivro.setText("");
                    JTF_EdicaoLivro.setText("");
                }
            }

        } else {
            if ("".equals(JTF_NomeDisco.getText()) || "".equals(JTF_AutorDisco.getText())) {
                JOptionPane.showMessageDialog(null, "É necessário preencher todos os dados!");
            } else {
                discos dvd = new discos();
                dvd.cadastro(JTF_NomeDisco.getText(), JTF_AutorDisco.getText(), JRad_Disco.isSelected());
            }
            JTF_NomeDisco.setText("");
            JTF_AutorDisco.setText("");
        }
    }//GEN-LAST:event_JB_CadastarActionPerformed

    private void JRad_DiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRad_DiscoActionPerformed
        JRad_CD.setSelected(false);
    }//GEN-LAST:event_JRad_DiscoActionPerformed

    private void JRad_CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRad_CDActionPerformed
        JRad_Disco.setSelected(false);
    }//GEN-LAST:event_JRad_CDActionPerformed

    private boolean converter() {
        try {
            setEd(Integer.parseInt(JTF_EdicaoLivro.getText()));
            return true;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "O campo 'Edição' deve ser composto "
                    + "de números! ");
            return false;
        }
    }

    public int getEd() {
        return ed;
    }

    public void setEd(int ed) {
        this.ed = ed;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Cadastar;
    private javax.swing.JButton JB_Voltar;
    private javax.swing.JLabel JLabel_Autor;
    private javax.swing.JLabel JLabel_Autor1;
    private javax.swing.JLabel JLabel_Nome1;
    private javax.swing.JLabel JLabel_NomeLivro;
    private javax.swing.JLabel JLabel_Título;
    private javax.swing.JRadioButton JRad_CD;
    private javax.swing.JRadioButton JRad_Disco;
    private javax.swing.JTextField JTF_AutorDisco;
    private javax.swing.JTextField JTF_AutorLivro;
    private javax.swing.JTextField JTF_EdicaoLivro;
    private javax.swing.JTextField JTF_NomeDisco;
    private javax.swing.JTextField JTF_NomeLivro;
    private javax.swing.JTabbedPane JTP_LivrosDiscos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
